
# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/answers/questions/477716/how-to-resolve-34no-hosted-parallelism-has-been-pu.html

trigger: none
#- main

pool:
  #vmImage: ubuntu-latest
  name: Default


jobs:

- job: build_lts
  steps:
    - bash: |
        echo "$rclone_limited_conf_base64" | base64 -d | sudo -n tee /rclone.conf > /dev/null
      displayName: write! secrets
      env:
        rclone_limited_conf_base64: $(rclone_limited_conf_base64)
    - bash: |
        ./ubiquitous_bash.sh _prepare_rclone_limited_file
        ./ubiquitous_bash.sh _getMinimal_cloud
      displayName: _getMinimal_cloud
    - bash: |
        ./ubiquitous_bash.sh _build_cloud_prepare
        ./ubiquitous_bash.sh _build_cloud_lts
      displayName: _build_cloud_lts
    - bash: |
        ./ubiquitous_bash.sh _export_cloud_lts
      displayName: _export_cloud_lts
    - bash: |
        ./ubiquitous_bash.sh _upload_cloud_lts
      displayName: _upload_cloud_lts

- job: build_mainline
  steps:
    - bash: |
        echo "$rclone_limited_conf_base64" | base64 -d | sudo -n tee /rclone.conf > /dev/null
      displayName: write! secrets
      env:
        rclone_limited_conf_base64: $(rclone_limited_conf_base64)
    - bash: |
        ./ubiquitous_bash.sh _prepare_rclone_limited_file
        ./ubiquitous_bash.sh _getMinimal_cloud
      displayName: _getMinimal_cloud
    - bash: |
        ./ubiquitous_bash.sh _build_cloud_prepare
        ./ubiquitous_bash.sh _build_cloud_mainline
      displayName: _build_cloud_mainline
    - bash: |
        ./ubiquitous_bash.sh _export_cloud_mainline
      displayName: _export_cloud_mainline
    - bash: |
        ./ubiquitous_bash.sh _upload_cloud_mainline
      displayName: _upload_cloud_mainline


