
# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/answers/questions/477716/how-to-resolve-34no-hosted-parallelism-has-been-pu.html

trigger: none
#- main

pool:
  #vmImage: ubuntu-latest
  name: Default

variables:
- name: rclone_limited_conf_base64


jobs:

- job: build_lts
  steps:
    - bash: |
        echo $(rclone_limited_conf_base64) | base64 -d | sudo -n tee /rclone.conf > /dev/null
      displayName: write! secrets
    - bash: |
        ./ubiquitous_bash.sh _prepare_rclone_limited_file
        ./_getMinimal_cloud
      displayName: _getMinimal_cloud
    - bash: |
        ./_build_cloud_prepare
        ./_build_cloud_lts
      displayName: _build_cloud_lts
    - bash: |
        ./_export_cloud_lts
      displayName: _export_cloud_lts
    - bash: |
        ./_upload_cloud_lts
      displayName: _upload_cloud_lts

- job: build_mainline
  steps:
    - bash: |
        echo $(rclone_limited_conf_base64) | base64 -d | sudo -n tee /rclone.conf > /dev/null
      displayName: write! secrets
    - bash: |
        ./ubiquitous_bash.sh _prepare_rclone_limited_file
        ./_getMinimal_cloud
      displayName: _getMinimal_cloud
    - bash: |
        ./_build_cloud_prepare
        ./_build_cloud_mainline
      displayName: _build_cloud_mainline
    - bash: |
        ./_export_cloud_mainline
      displayName: _export_cloud_mainline
    - bash: |
        ./_upload_cloud_mainline
      displayName: _upload_cloud_mainline


