version: 0.2

# WARNING: May be untested.


# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-cli-create-build-spec.html
#  'You cannot change the spelling of these build phase names, and you cannot create more build phase names.'


# amazon.command
#  'You can use Parameter Store in Amazon EC2 Systems Manager to store sensitive values required by your builds. For example, passwords and AWS access IDs.'

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
#  'strongly discourage the storing of sensitive values, especially AWS access key IDs and secret access keys, in environment variables' 'recommend that you use parameter-store or secrets-manager mapping instead'
#  'must add the ssm:GetParameters action to your CodeBuild service role'

# https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/
#  'extend the maximum session duration for an IAM role to up to 12 hours using the IAM console or CLI'
#  'new feature is available in all AWS Regions where AWS Security Token Service (AWS STS) is available'
# > Build projects -> 'project' -> Build details -> Service role 'link' ->
#  'Maximum session duration' '1 hour' 'Edit'


env:
  #variables:
     # key: "value"
     # key: "value"
  parameter-store:
      rclone_limited_conf_base64: "rclone_limited_conf_base64"
  #secrets-manager:
     #key: rclone_limited_conf_base64
  #exported-variables:
     # - variable
     # - variable
  git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - ./ubiquitous_bash.sh _prepare_rclone_limited_file
      - ./ubiquitous_bash.sh _gitBest submodule update --init --depth 1 --recursive
      - ./_getMinimal_cloud
  build:
    commands:
      #- ./_build_cloud_lts
      #- ./_build_cloud_mainline
      - ./_build_cloud
  post_build:
    commands:
      #- ./_export_cloud_lts
      #- ./_export_cloud_mainline
      - ./_export_cloud
      #- ./_upload_cloud_lts
      #- ./_upload_cloud_mainline
      - ./_upload_cloud
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
