version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - onBuild

jobs:
  onBuild:
    steps:
      - checkout
      - run:
          name: _getMinimal_cloud
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _getMinimal_cloud
          when: always
      - run:
          name: _fetchKernel
          command: |
            ./ubiquitous_bash.sh _fetchKernel
      #- run:
          #name: _build_cloud
          #command: |
            #./ubiquitous_bash.sh _build_cloud
      - run:
          name: _export_cloud
          command: |
            ./ubiquitous_bash.sh _export_cloud






