
workflows:
  version: 2
  build:
    triggers:
      filters:
        branches:
          ignore:
            - main
  jobs:
    - build


jobs:
  build:
    machine:
      image: ubuntu-2004:current
    #resource_class: large
    resource_class: medium
    steps:
      - checkout
      - run:
          name: _getMinimal_cloud
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _getMinimal_cloud
          when: always
      - run:
          name: _fetchKernel
          command: |
            ./ubiquitous_bash.sh _fetchKernel
      #- run:
          #name: _build_cloud
          #command: |
            #./ubiquitous_bash.sh _build_cloud
      - run:
          name: _export_cloud
          command: |
            ./ubiquitous_bash.sh _export_cloud





