
# https://discuss.circleci.com/t/branch-filtering-ignore/24301
workflows:
  version: 2
  commit:
    jobs:
      - onCommit
  #all:
    #jobs:
      #- build:
          #filters:
            #branches:
              #only: /^doNotMatch/
              #only: main
              #ignore:
                #- /.*/
                #- /pull.*/
                #- /push.*/
              #ignore: /.*/
              #ignore: /pull.*/
              #ignore: /push.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main


jobs:
  onCommit:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: _true
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _true
  build:
    machine:
      image: ubuntu-2004:current
    #resource_class: large
    resource_class: medium
    steps:
      - checkout
      - run:
          name: _getMinimal_cloud
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _getMinimal_cloud
          when: always
      - run:
          name: _fetchKernel
          command: |
            ./ubiquitous_bash.sh _fetchKernel
      #- run:
          #name: _build_cloud
          #command: |
            #./ubiquitous_bash.sh _build_cloud
      - run:
          name: _export_cloud
          command: |
            ./ubiquitous_bash.sh _export_cloud





