
# https://discuss.circleci.com/t/branch-filtering-ignore/24301
# https://circleci.com/docs/2.0/workflows/#nightly-example
# https://circleci.com/docs/2.0/workflows/
# https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows
workflows:
  version: 2
  commit:
    jobs:
      - onCommit
  #regular:
    #triggers:
      #- schedule:
          #cron: "0 0 * * *"
          #filters:
            #branches:
              #only:
                #- main
    #jobs:
      #- build
  all:
    when:
      and: # All must be true to trigger
        - equal [ build, << pipeline.parameters.param1 >> ]
    jobs:
      - build:
          filters:
            branches:
              #only: /^doNotMatch/
              only: main
              #ignore:
                #- /.*/
                #- /pull.*/
                #- /push.*/
              #ignore: /.*/
              #ignore: /pull.*/
              #ignore: /push.*/


jobs:
  onCommit:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: _messagePlain_good nothing
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _messagePlain_good 'good: nothing'
  build:
    machine:
      image: ubuntu-2004:current
    #resource_class: large
    resource_class: medium
    steps:
      - checkout
      - run:
          name: _getMinimal_cloud
          #shell: /bin/bash -eo pipefail
          command: |
            ./ubiquitous_bash.sh _getMinimal_cloud
          when: always
      - run:
          name: _fetchKernel
          command: |
            ./ubiquitous_bash.sh _fetchKernel
      #- run:
          #name: _build_cloud
          #command: |
            #./ubiquitous_bash.sh _build_cloud
      - run:
          name: _export_cloud
          command: |
            ./ubiquitous_bash.sh _export_cloud





