
name: interactive
on:
  workflow_dispatch:



jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
      
      #name: _getMost_ubuntu20
      #./ubiquitous_bash.sh _getMost_ubuntu20

