
name: interactive
# https://github.community/t/self-hosted-not-using-bashrc/18358
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_dispatch:

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: _getMinimal_cloud
      #$RUNNER_WORKSPACE
      #sudo touch /continue
      #bash -i
      run: |
        ./ubiquitous_bash.sh _getMinimal_cloud
      timeout-minutes: 45
      # https://github.com/marketplace/actions/debugging-with-tmate
      #$RUNNER_WORKSPACE
      #sudo touch /continue
      #bash -i
      # Type 'q' at the 'Web shell' or use SSH .
    - name: bashrc
      run: |
        source ~/.bashrc
    - name: Setup tmate session
      #if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      #ssh -i <path-to-key> <tmate-connection-string>
      #with:
        #limit-access-to-actor: true
      timeout-minutes: 90






