
name: interactive
on:
  workflow_dispatch:

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: _getMinimal_cloud
      #$RUNNER_WORKSPACE
      #sudo touch /continue
      #bash -i
      run: |
        ./ubiquitous_bash.sh _getMinimal_cloud
      timeout-minutes: 45
    - name: .bash_profile
      run: |
        echo '. ~/.bashrc' > ~/.bash_profile
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      #ssh -i <path-to-key> <tmate-connection-string>
      #with:
        #limit-access-to-actor: true
      timeout-minutes: 90






