
name: interactive
on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  #schedule:
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 6,2,4'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: _getMinimal_cloud
      # $RUNNER_WORKSPACE
      run: |
        ./ubiquitous_bash.sh _getMinimal_cloud
      timeout-minutes: 45
    - name: _fetchKernel
      run: |
        ./ubiquitous_bash.sh _fetchKernel
      timeout-minutes: 45
    #- name: _build_cloud
      #run: |
        #./ubiquitous_bash.sh _build_cloud
      #timeout-minutes: 330
    - name: _export_cloud
      run: |
        ./ubiquitous_bash.sh _export_cloud
      timeout-minutes: 90
    - name: Upload 
        uses: Difegue/action-megacmd@master
        with:
          args: put ./_local/_export/linux-lts-amd64-debian.tar.gz /Public/mirage335KernelBuild/
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      timeout-minutes: 90
    # https://github.com/marketplace/actions/debugging-with-tmate
    # $RUNNER_WORKSPACE
    # sudo touch /continue
    # bash -i
    # source ~/.bashrc
    # Type 'q' at the 'Web shell' or use SSH .
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      # ssh -i <path-to-key> <tmate-connection-string>
      with:
        limit-access-to-actor: true
      timeout-minutes: 5






